config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about' 
  resources :articles 
  get "signup", to: 'users#new'
  #post 'users', to:'users#create'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord 
    belongs_to :user
    validates :title, presence: true, length: {minimum:6, maximum:100}
    validates :description, presence: true,  length: {minimum:10, maximum:300}
end

app/models/user.rb
class User < ApplicationRecord
    before_save {self.email = email.downcase}
    has_many :articles
    validates :username, presence: true, 
                      uniqueness: { case_sensitive: false }, 
                      length: { minimum: 3, maximum: 25 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, 
                      uniqueness: { case_sensitive: false }, 
                      length: { maximum: 105 },
                      format: { with: VALID_EMAIL_REGEX }

    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    
    before_action :set_article, only: [:show, :edit, :update, :destroy]
     
    def show
    end

    def index
        @articles = Article.paginate(page: params[:page], per_page: 3)
    end

    def new
        @article = Article.new
    end

    def edit 
    end

    def create
        @article = Article.new(article_params)
        @article.user = User.first
        if @article.save
            flash[:notice] = "Article was created successfully."
            redirect_to @article
        else
            render 'new'
        end    
    end

    def update
        if @article.update(article_params)
        flash[:notice] = "Article was updated successfully."
        redirect_to @article
        else
        render 'edit'
        end
    end

    def destroy
        @article.destroy
        redirect_to articles_path
      end 

      private

      def set_article 
        @article = Article.find(params[:id])
      end  

      def article_params
        params.require(:article).permit(:title, :description)
      end  

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
    end
    def about 
    end   
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = "Logged in successfully"
      redirect_to user
    else
      flash.now[:alert] = "There was something wrong with your login details"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Logged out"
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController 
    def show 
        @user = User.find(params[:id])
        @articles = @user.articles.paginate(page: params[:page], per_page: 3) 
    end
    
    def index
        @users = User.paginate(page: params[:page], per_page: 3) 
    end 


    def new
        @user = User.new
    end

    def edit 
        @user = User.find(params[:id])
    end

    def update
        @user = User.find(params[:id])
        if @user.update(user_params)
            flash[:notice] = "Your account information was successfully updated"
            redirect_to @user
        else 
            render 'edit'
        end
    end

    def create 
        @user = User.new(user_params)
        if @user.save
            flash[:notice] = "Welcome to the Alphog Blog #{@user.username}, you have successfully signed up"
            redirect_to articles_path
        else 
            render 'new'
        end
    end

    private

    def user_params
        params.require(:user).permit(:username, :email, :password)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

    def gravatar_for(user, options = {size: 80})
        email_address = user.email.downcase 
        hash = Digest::MD5.hexdigest(email_address)
        size = options[:size]
        gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
        image_tag(gravatar_url, alt: user.username)
    end


end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article.html.erb
<table>
    <thead>
    <tr>
    <th>User_id</th>
    <th>Title</th>
    <th>Description</th>
    <th colspan='3'>Actions</th>
    </tr>
    </thead>
    <tbody>
    <% @articles.each do |article| %>
        <tr>
        <td><%= link_to article.user.username, user_path(article.user) if article.user %></td>
            <td><%= article.title %></td>
            <td><%= article.description %></td>
            <td><%= link_to 'Show', article_path(article) %></td>
            <td><%= link_to 'Edit', edit_article_path(article) %></td>
            <td><%= link_to 'Delete', article_path(article), data: { turbo_method: :delete, turbo_confirm: "Are You Sure?" } %></td>
        </tr>
        <% end %>
    </tbody>
</table> 

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>

<%= form_with(model: @article, local: true) do |f| %>

  <p>
    <%= f.label :title %><br/>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :description %><br/>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/articles/edit.html.erb
<h1>Edit article</h1>

<%= render 'form' %>

<%= link_to 'Cancel and return to articles listing', articles_path %>

app/views/articles/index.html.erb
<h1>Articles Listing Feature</h1>

<div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
  </div>

  <%= render 'article' %>

  <div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
  </div>

<p>
  <%= link_to 'Create new article', new_article_path %>
</p>

app/views/articles/new.html.erb
<h1>Create a new article</h1>

<%= render 'form' %>

<%= link_to 'Return to articles listing', articles_path %>

app/views/articles/show.html.erb
<h1>Showing article details</h1>

by <%= @article.user.username if @article.user %>
<%= link_to gravatar_for(@article.user), user_path(@article.user) %>
<p><strong>Title: </strong> <%= @article.title %></p>
<p><strong>Description:  </strong><%= @article.description %></p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Delete', article_path(@article), data: { turbo_method: :delete, turbo_confirm: "Are You Sure?" } %> |
<%= link_to 'Return to articles listing', articles_path %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
    <%= msg %>
    <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Alpha-Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render 'layouts/messages' %> <br/>
  <%= link_to 'Log in', login_path %>
  <%= link_to 'Logout', logout_path, data: { turbo_method: :delete } %> 
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>This is About Page!</h1>

<%= link_to 'Articles listing', articles_path %> |
<%= link_to 'Home page', root_path %>

app/views/pages/home.html.erb
<h1>Hi! This is Home Page!</h1>

<%= link_to 'Articles listing', articles_path %> |
<%= link_to 'About page', about_path %> | 
<%= link_to 'Sign up!', signup_path %>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <h2>The following errors prevented the <%= obj.class.name.downcase %> from being saved</h2>
  <ul>
    <% obj.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>

<%= form_with(model: @user, local: true) do |f| %>

  <p>
    <%= f.label :username %><br/>
    <%= f.text_field :username %>
  </p>

  <p>
    <%= f.label :email %><br/>
    <%= f.email_field :email %>
  </p>

  <p>
  <%= f.label :password %><br/>
  <%= f.password_field :password %>
</p>


  <p>
    <%= f.submit(@user.new_record? ? "Sign up" : "Update acount")  %>
  </p>

<% end %>

app/views/users/edit.html.erb
<h1>Edit Your Profile</h1>

<%= render 'form' %>

<%= link_to 'Return to articles listing', articles_path %>

app/views/users/index.html.erb
<h1 class="text-center">Alpha Bloggers</h1>

<div class="flickr_pagination">
    <%= will_paginate @users, :container => false %>
  </div>

<table>
    <thead>
    <tr>
    <th>User Name</th>
    <th>Image</th>
    <th>No of Articles</th>
    <th colspan='2'>Actions</th>
    </tr>
    </thead>
    <tbody>
    <% @users.each do |user| %>
        <tr>
        <td><%= link_to user.username, user %></td>
            <td><%= link_to gravatar_for(user, size: 150), user %></td>
            <td><%= pluralize(user.articles.count, "artilce") %></td>
            <td><%= link_to 'View Profile', user %></td>
            <td><%= link_to 'Edit Profile', edit_user_path(User) %></td>
        </tr>
        <% end %>
    </tbody>
</table> 

<div class="flickr_pagination mb-4">
    <%= will_paginate @users, :container => false %>
  </div>

app/views/users/new.html.erb
<h1>Sign up for Alpha Blog</h1>

<%= render 'form' %>

<%= link_to 'Return to articles listing', articles_path %>

app/views/users/show.html.erb
<h1><%= @user.username %>'s profile</h1>

<%= gravatar_for @user, size: 200 %>

<%= link_to "Edit your profile", edit_user_path(@user) %>

<h3>Articles</h1>

<div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
  </div>

<%= render 'articles/article' %>

<div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
  </div>